title: sourceAFRICA
sub-title: 'Africa''s premier repository for actionable documents'

description: 'Africa''s premier repository for actionable documents'

url: https://sourceafrica.net
enforce_ssl: sourceafrica.net

dc_url: https://dc.sourceafrica.net

github-url: https://github.com/CodeForAfrica/sourceAFRICA.app-Briefcase
api-url: https://sourceafrica.net/help/api

newsletter: http://eepurl.com/burS8v
google-analytics:


home_bg_url: /img/bg/docs.png

twitter: '@Code4Africa'
github: CodeForAfrica

