title: Briefcase
sub-title: Document Leaks from KMOFA

url: https://briefcase.sourceafrica.net
enforce_ssl: briefcase.sourceafrica.net

github-url: https://github.com/CodeForAfrica/sourceAFRICA.app-Briefcase
api-url: https://sourceafrica.net/help/api

newsletter: http://eepurl.com/burS8v
google-analytics:


home_bg_url: /img/bg/main.jpg

